#Made by BGHDNetwork(Noodles)
#Suport Discord: https://bghddevelopment.com/discord
#Version 0.7
#Plugin Page: https://www.spigotmc.org/resources/44518/
#=======================================================
#Permssion: ultimatefreeze.update
Update:
  Enabled: true
#Enables if there is a message on-join when the plugin is outdated. 
#=======================================================
#Permssions:
# /freeze or /ss - ultimatefreeze.freeze
# Notification when someone leaves when frozen - ultimatefreeze.quitmessage
#ultimatefreeze.override - Can't be frozen
#=======================================================
UseGUI:
  Enabled: true
#When set to true when the player is frozen they will see a GUI.
#When set to false when the player is frozen they will see a chat message.
#=======================================================
#Plugin Options (When Frozen)
GiveBlindness:
  Enabled: true
#If set to true, the player will be given blindness when frozen.

StopBlockBreak:
  Enabled: true
#If set to true, the player will not be able to break blocks when frozen.

StopBlockPlace:
  Enabled: true
#If set to true, the player will not be able to place blocks when frozen.

StopPlayerPVP:
  Enabled: true
#If set to true, the player will not be able to pvp when frozen.

StopFoodLevelChange:
  Enabled: true
#If set to true, the player will not lose hunger when frozen.

StopCommandUsage:
  Enabled: true
#If set to true, the player will not be able to use commands when frozen.

BanOnLeave:
  Enabled: false
#If set to true, if a player leaves while frozen they will be banned.

BanCommand: "ban %target% logging out while frozen"
#Command run when a user logs out while frozen. BanOnLeave must be set to true.\
#DO NOT PUT THE /